// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaAnimaisMVC.Data;

#nullable disable

namespace SistemaAnimaisMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251113132857_CriarBanco")]
    partial class CriarBanco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaAnimaisMVC.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.ToTable("tabelaAnimal");

                    b.HasDiscriminator<string>("Tipo").HasValue("Animal");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SistemaAnimaisMVC.Models.Elefante", b =>
                {
                    b.HasBaseType("SistemaAnimaisMVC.Models.Animal");

                    b.HasDiscriminator().HasValue("Elefante");
                });

            modelBuilder.Entity("SistemaAnimaisMVC.Models.Leão", b =>
                {
                    b.HasBaseType("SistemaAnimaisMVC.Models.Animal");

                    b.HasDiscriminator().HasValue("Leão");
                });
#pragma warning restore 612, 618
        }
    }
}
